---
# tasks file for fixes

# via https://www.linuxbabe.com/ubuntu/disable-apport-error-reporting-ubuntu-16-04-lts
- name: disable apport error reporting
  become: yes
  lineinfile:
    path: /etc/default/apport
    regexp: '^enabled='
    line: 'enabled=0'

# via https://askubuntu.com/questions/446395/how-to-turn-off-software-updater-xubuntu
- name: remove update notifier
  become: yes
  apt:
    name: update-notifier
    state: absent
  when: ansible_pkg_mgr == 'apt'
