---

- name: nvm | download nvm install script
  get_url:
    dest: /tmp/install.sh
    mode: 0755
    url: https://raw.githubusercontent.com/creationix/nvm/v{{ nvm_version }}/install.sh

- name: nvm | run nvm install script
  shell: /tmp/install.sh
  args:
    creates: "{{ nvm_dest }}/nvm.sh"
