---
# Tasks file for Vagrant

- name: "Install Vagrant"
  apt:
    deb: https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.deb
    install_recommends: no
  when: ansible_pkg_mgr == 'apt'
