---
# Install Visual Studio Code
# Via: https://code.visualstudio.com/docs/setup/linux

- name: "add microsoft key"
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
  when: ansible_pkg_mgr == 'apt'

- name: "add vscode repo"
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    filename: vscode
  when: ansible_pkg_mgr == 'apt'

- name: "install code"
  apt:
    name: code
    install_recommends: no
  when: ansible_pkg_mgr == 'apt'

# Via: https://www.microsoft.com/net/learn/dotnet/hello-world-tutorial
- name: Register Microsoft key and feed
  apt:
    deb: https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
    install_recommends: no

- name: "install dotnet-sdk-2.1"
  apt:
    name: dotnet-sdk-2.1
    install_recommends: no
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'
