# apt tasks file for smartgit role

- name: "apt | ensure ppa:eugenesan/ppa present"
  apt_repository:
    repo: ppa:eugenesan/ppa
    filename: "eugenesan"
    state: present
    update_cache: yes

- name: "apt | ensure SmartGit present"
  apt:
    name: "smartgit"
    state: present
