# apt tasks file for smartgit role

- name: add smartgit repo
  become: yes
  apt_repository:
    repo: ppa:eugenesan/ppa
    filename: "eugenesan"
    state: present
    update_cache: yes

- name: install smartgit
  become: yes
  apt:
    name: "smartgit"
    state: present
