# apt tasks file for sublimetext role
# via https://www.sublimetext.com/docs/3/linux_repositories.html#apt

- name: install sublime key
  become: yes
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: install common packages
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - apt-transport-https
  when: ansible_pkg_mgr == 'apt'

- name: add sublime repo
  become: yes
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    filename: "sublimetext"
    state: present
    update_cache: yes

- name: install sublimetext
  become: yes
  apt:
    name: "sublime-text"
    state: present
