# apt tasks file for sublimetext role
# via https://www.sublimetext.com/docs/3/linux_repositories.html#apt

- name: "Install Sublime Text GPG key"
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: "Ensure apt is set up to work with https sources"
  apt:
    name: apt-transport-https
    state: present

- name: "Select Sublime Text channel to use"
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    filename: "sublimetext"
    state: present
    update_cache: yes

- name: "Install Sublime Text"
  apt:
    name: "sublime-text"
    state: present

