---

- name: "install apt-transport-https"
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - apt-transport-https
  when: ansible_pkg_mgr == 'apt'

- name: "add google's apt-key"
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
  when: ansible_pkg_mgr == 'apt'

- name: "add kubernetes repo"
  apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-{{ ansible_lsb.codename }} main"
    filename: kubernetes
  when: ansible_pkg_mgr == 'apt'

- name: "install kubectl"
  apt:
    name: kubectl
  when: ansible_pkg_mgr == 'apt'

...
