---
# Tasks file for Java role

- name: install java
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - openjdk-8-jre
    - openjdk-8-jdk
  when: ansible_pkg_mgr == 'apt'

# SmartGit 18.1 fails to start with JRE 9 preview error message
- name: select correct java version
  become: yes
  alternatives:
    name: java
    path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  when: ansible_pkg_mgr == 'apt'

...
