---
# Install Docker CE

- name: install common packages
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
  when: ansible_pkg_mgr == 'apt'

- name: install docker key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  when: ansible_pkg_mgr == 'apt'

- name: install docker repo
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
  when: ansible_pkg_mgr == 'apt'

- name: install docker ce
  become: yes
  apt:
    name: docker-ce
  when: ansible_pkg_mgr == 'apt'

- name: "add `{{ docker_user }}` to docker group"
  become: yes
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes
  when: docker_user != 'root'

...
