---
# Install Docker CE

- name: "Install packages to allow apt to use a repository over HTTPS"
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
  when: ansible_pkg_mgr == 'apt'

- name: "Add Docker’s official GPG key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  when: ansible_pkg_mgr == 'apt'

- name: "Setup the stable Docker repository"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
  when: ansible_pkg_mgr == 'apt'

- name: "Install Docker CE"
  apt:
    name: docker-ce
  when: ansible_pkg_mgr == 'apt'

- name: "Add user `{{ docker_user }}` to docker group"
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes
  when: docker_user != 'root'

- name: "Run Hello World in a docker container"
  shell: "docker run --rm hello-world"
  changed_when: False

...
