---

- name: "Add Insomnia key"
  apt_key:
    url: https://insomnia.rest/keys/debian-public.key.asc
    state: present
  when: ansible_pkg_mgr == 'apt'

- name: "Add insomnia repo"
  apt_repository:
    repo: "deb https://dl.bintray.com/getinsomnia/Insomnia /"
    filename: "insomnia"
    state: present
  when: ansible_pkg_mgr == 'apt'

- name: "Install insomnia"
  apt:
    name: insomnia
    state: present
  when: ansible_pkg_mgr == 'apt'

...
